# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
  - name: Setup Node.js environment
  uses: actions/setup-node@v2.1.0
  with:
  version: 12
  - name: npm/yarn/pnpm install
  uses: Jaid/action-npm-install@v1.2.4
  with:
  # Npm Command
  cmd: install
  
  -name:creating build
   run: npm build
   
  -name: installing surge
   run: npm install -g surge
   
   -name: deploying on surge
    run: surge ./build https://bootcampc2.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
